name: zbctl # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '8.6.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: zbctl is the command line interface to interact with Camunda 8 and Zeebe # 79 char long summary
description: |
  zbctl is a command line interface for Camunda Platform 8 designed to create and read resources inside a Zeebe broker.
  It can be used for regular development and maintenance tasks such as:
  * Deploying process and decision models
  * Creating process instances and job workers
  * Activating, completing, or failing jobs
  * Updating variables and retries
  * Viewing cluster status

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
platforms:
  amd64:
  arm64:

apps:
  zbctl:
    command: bin/zbctl
    plugs:
      - home
      - network

parts:
  zbctl:
    plugin: go
    source: https://github.com/camunda-community-hub/zeebe-client-go.git
    source-tag: v$CRAFT_PROJECT_VERSION
    build-snaps:
      - go/1.21/stable
    override-build: |
      cd cmd/zbctl
      # Set GOARCH based on the target architecture
      case $CRAFT_ARCH_BUILD_FOR in
        amd64)
          export GOARCH=amd64
          ;;
        arm64)
          export GOARCH=arm64
          ;;
        *)
          echo "Unsupported architecture: $CRAFT_ARCH_BUILD_FOR"
          exit 1
          ;;
      esac
      CGO_ENABLED=0 GOOS=linux go build -a -tags netgo -ldflags "-w -X github.com/camunda-community-hub/zeebe-client-go/v8/cmd/zbctl/internal/commands.Version=${CRAFT_PROJECT_VERSION} -X github.com/camunda-community-hub/zeebe-client-go/v8/cmd/zbctl/internal/commands.Commit=$(git rev-parse HEAD)" -o $CRAFT_PART_INSTALL/bin/zbctl main.go
    stage:
      - bin/zbctl
    prime:
      - bin/zbctl
